adminbyid con id de instituciones, permisos, login-admin trae también…
Portal-Pacientes-La-Rioja/portal_paciente_LR_backend pull request #122
Opened 2023-05-31 14:49 UTC by ifdamianboden

… is_admin y is superadmin

2023-05-31 14:59 UTC, eamanu requested changes

2023-05-31 14:59 UTC, eamanu commented on app/models/permission.py
> +                'Create an user admin', "create_admin", "admins","adminbyid","onoffadmin"]
Los endpoints  que agregaste acá son solo del superadmin. Revisalos.

2023-05-31 14:59 UTC, eamanu commented on app/routes/auth.py
> +            }
No devolver el is admin y el is superadmin eso ya se puede deducir del sub del tokeb

2023-05-31 14:59 UTC, eamanu commented on app/models/user.py
> +        is_admin: int, institutions: list[institutions]
Esot me hace ruido. Fíjate como esta hecho la parte de institución y el listado de especialidades

2023-05-31 21:32 UTC, eamanu commented
También fíjate que tiene conflictos

2023-05-31 21:39 UTC, ifdamianboden commented
Okk Emma, más tarde subo.

El mié., 31 may. 2023 18:32, Emmanuel Arias ***@***.***>
escribió:

> También fíjate que tiene conflictos
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Portal-Pacientes-La-Rioja/portal_paciente_LR_backend/pull/122#issuecomment-1570989607>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWRAMPFZYRTBGSBMQZE3UTLXI62HTANCNFSM6AAAAAAYVSXMDA>
> .
> You are receiving this because you authored the thread.Message ID:
> <Portal-Pacientes-La-Rioja/portal_paciente_LR_backend/pull/122/c1570989607
> @github.com>
>

2023-06-02 10:25 UTC, eamanu approved these changes

2023-06-02 10:25 UTC, eamanu commented on app/routes/auth.py
> +            "id": userid.id
Perdón estaba bien este cambio del is_superadmin, eso me pasa po no mirar el trello. Ya lo volya revertear

2023-06-02 10:25 UTC, merged