added study upload endpoint with validation checks
Portal-Pacientes-La-Rioja/portal_paciente_LR_backend pull request #152
Opened 2023-08-02 04:46 UTC by cquevedox

2023-08-06 15:41 UTC, eamanu requested changes
Cuando ejecuto tengo este error

```
curl -X 'POST' \
  'http://127.0.0.1:8000/portalpaciente/api/v1/upload-study?person_id=1&description=test&study_type_id=1' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'study=@test.png;type=image/png' \
-H 'Authorization: Bearer <token>
{"value":"","message":"Error: (pymysql.err.DataError) (1406, \"Data too long for column 'file_path' at row 1\")\n[SQL: INSERT INTO studies (id_person, id_study_type, study_name, description, file_path, upload_date) VALUES (%(id_person)s, %(id_study_type)s, %(study_name)s, %(description)s, %(file_path)s, now())]\n[parameters: {'id_person': 1, 'id_study_type': 1, 'study_name': 'test.png', 'description': 'test', 'file_path': b'iVBORw0KGgoAAAANSUhEUgAAB4AAAAQ4CAYAAADo08FDAAAABHNCSVQICAgIfAhkiAAAABl0RVh0U29mdHdhcmUAZ25vbWUtc2NyZWVuc2hvdO8Dvz4AAAAmdEVYdENyZWF0aW9uIFRpbWUAdmll ... (212307 characters truncated) ... AAAAAAACUiMLqVSuLbV0EAAAAAAAAAG9cXV1damtrzQAGAAAAAAAAKBUVdXV1bV0DAAAAAAAAANtg7dp1qa+vT0VtbW1b1wIAAAAAAADANli3fkNWr1qZ/wc2/W2c3Vk1cwAAAABJRU5ErkJggg=='}]\n(Background on this error at: https://sqlalche.me/e/14/9h9h)","code":500,"status":false}
```

Por favor revisalo. (Hacé un pull antes porque agregué la migration, así tengas para probar local)

2023-08-06 15:41 UTC, eamanu commented on app/gear/studies/studies.py
> +        if file_extension not in ALLOWED_EXTENSIONS:
agregaría además un chequeo de MIMETYPE, por ejemplo este modulo lo hace https://pypi.org/project/filetype/, por las dudas.

2023-08-06 15:41 UTC, eamanu commented on app/models/study_type.py
> +class StudyType(Base):
Cuales son los valores de StuyTypes que tendríamos que tener guardados en la DB?

2023-08-06 16:16 UTC, cquevedox commented on app/models/study_type.py
> +class StudyType(Base):
Estudios de Imágenes:
Estudios de Laboratorio:
Estudios Observacionales:
Resumen de Historia Clínica:
Otros:

2023-08-07 14:01 UTC, eamanu commented
Excelente, como hablamos agregalo en la migración.


On Sun, Aug 6, 2023 at 1:16 PM Cristian Quevedo ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In app/models/study_type.py
> <https://github.com/Portal-Pacientes-La-Rioja/portal_paciente_LR_backend/pull/152#discussion_r1285237860>
> :
>
> > @@ -0,0 +1,16 @@
> +from sqlalchemy import Column, Integer, String
> +from sqlalchemy.orm import relationship
> +
> +from app.config.database import Base
> +
> +
> +class StudyType(Base):
>
> Estudios de Imágenes:
> Estudios de Laboratorio:
> Estudios Observacionales:
> Resumen de Historia Clínica:
> Otros:
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Portal-Pacientes-La-Rioja/portal_paciente_LR_backend/pull/152#discussion_r1285237860>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB2AYO5OO3KT46XG7XHUWC3XT67N3ANCNFSM6AAAAAA3AWB3XU>
> .
> You are receiving this because you were assigned.Message ID:
> <Portal-Pacientes-La-Rioja/portal_paciente_LR_backend/pull/152/review/1564174342
> @github.com>
>

2023-08-10 19:11 UTC, eamanu approved these changes

2023-08-10 19:11 UTC, merged