visualización de id en getinstitutions
Portal-Pacientes-La-Rioja/portal_paciente_LR_backend pull request #67
Opened 2023-04-12 03:01 UTC by ifdamianboden

2023-04-12 03:02 UTC, ifdamianboden commented
Ya se visualiza id en getinstitutions

2023-04-14 21:06 UTC, eamanu requested changes

2023-04-14 21:06 UTC, eamanu commented on app/schemas/institutions.py
> +    lat: Optional[int]
lat, long son float, no int.

2023-04-14 21:22 UTC, eamanu commented
@ifdamianboden tambien fijate los conflictos

2023-04-17 14:32 UTC, eamanu approved these changes

2023-04-17 14:32 UTC, merged