fixed geolocalization module
Portal-Pacientes-La-Rioja/portal_paciente_LR_backend pull request #70
Opened 2023-04-17 15:38 UTC by cquevedox

closes #65

2023-04-17 19:01 UTC, eamanu requested changes

2023-04-17 19:01 UTC, eamanu commented on app/gear/geolocation/geolocation_utils.py
> +        self.geolocator = Nominatim(user_agent="portal-paciente", timeout=5)
subilo a 15, just in case.

2023-04-18 12:59 UTC, cquevedox commented on app/gear/geolocation/geolocation_utils.py
> +        self.geolocator = Nominatim(user_agent="portal-paciente", timeout=5)
listo

2023-04-20 13:52 UTC, eamanu approved these changes

2023-04-20 13:52 UTC, eamanu commented
Ahi lo probé. Gracias!

2023-04-20 13:53 UTC, merged